### ISSUE TITLE
Exception parsing NTstation

### ISSUE THREAD

**Issue by ike709** [mumencoder/Clopendream-parser#1]
Code: https://github.com/ike709/NTstation13/tree/clod

Exception:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ClopenDream.LabelException: Exception of type 'ClopenDream.LabelException' was thrown.
   at ClopenDream.LabelContext.Error() in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Labels\Context.cs:line 98
   at ClopenDream.LabelContext.Parse(Func`2 parser, Node node, Boolean uncurse, Boolean label, Boolean optional) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Labels\Context.cs:line 40
   at ClopenDream.LabelContext.ParseNodes(Func`2 parser, List`1 nodes, Boolean label, Boolean optional, Int32 length) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Labels\Context.cs:line 88
   at ClopenDream.LabelContext.CheckObjectVarDecl(Node node) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Labels\Toplevel\Toplevel.cs:line 36
   at ClopenDream.LabelContext.Parse(Func`2 parser, Node node, Boolean uncurse, Boolean label, Boolean optional) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Labels\Context.cs:line 40
   at ClopenDream.LabelContext.CheckTopLevel(Node node) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Labels\Toplevel\Toplevel.cs:line 12
   at ClopenDream.Parser.BeginParse(TextReader input, FileInfo original_file) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenAST\Parse\Parser.cs:line 108
   at ClopenDream.Program.ClopenParse(FileInfo byond_codetree, DirectoryInfo working_dir, DMASTFile open_root, DirectoryInfo output_dir) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenDreamCommandLine\Program.cs:line 172
   at ClopenDream.Program.ParseHandler(FileInfo byond_codetree, FileInfo dm_original, DirectoryInfo working_dir, FileInfo json_file, String mode) in C:\Users\main\Documents\GitHub\CLOD\Clopendream-parser\ClopenDreamCommandLine\Program.cs:line 82
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
   ```

**Comment by ike709** [comment]
Output before exception:
```
clopen parse
869178 CheckPathTerminator leave is True
869176 CheckPathDecl leave is True
869175 CheckPathDecl leave is True
869174 CheckObjectVarDecl leave is True
869180 CheckProcDecl enter
869180 CheckProcDecl leave is False
869180 CheckProcOverride enter
869181 CheckProcHeader enter
869181 CheckProcHeader leave is False
869180 CheckProcOverride leave is False
869180 CheckObjectVarDecl enter
869181 CheckPathDecl enter
869181 CheckPathTerminated enter
869181 CheckPathTerminated leave is False
869182 CheckPathDecl enter
869182 CheckPathTerminated enter
869182 CheckPathTerminated leave is False
869183 CheckPathDecl enter
869183 CheckPathTerminated enter
869183 CheckPathTerminated leave is True
869185 CheckPathTerminator enter
869185 CheckVarInit enter
869186 CheckVarInitRValue enter
869186 CheckExpression enter
869186 CheckSelfExpression enter
869186 CheckSelfExpression leave is False
869186 CheckOperatorExpression enter
869186 CheckOperatorExpression leave is False
869186 CheckChainExpression enter
869186 CheckChainExpression leave is False
869186 CheckLiteralExpression enter
869186 CheckNumericLiteral enter
869186 CheckNumericLiteral leave is False
869186 CheckStringLiteral enter
869186 CheckStringLiteral leave is False
869186 CheckResourceLiteral enter
869186 CheckResourceLiteral leave is False
869186 CheckPathConstant enter
869186 CheckPathConstant leave is False
869186 CheckNullLiteral enter
869186 CheckNullLiteral leave is False
869186 CheckLiteralExpression leave is False
869186 CheckIndexExpression enter
869186 CheckIndexExpression leave is False
869186 CheckListExpression enter
869186 CheckListExpression leave is True
869186 CheckExpression leave is True
869186 CheckVarInitRValue leave is True
869185 CheckVarInit leave is True
869185 CheckPathTerminator leave is True
869183 CheckPathDecl leave is True
869182 CheckPathDecl leave is True
869181 CheckPathDecl leave is True
869180 CheckObjectVarDecl leave is True
869187 CheckProcDecl enter
869187 CheckProcDecl leave is False
869187 CheckProcOverride enter
869188 CheckProcHeader enter
869188 CheckProcHeader leave is False
869187 CheckProcOverride leave is False
869187 CheckObjectVarDecl enter
869188 CheckPathDecl enter
869188 CheckPathTerminated enter
869188 CheckPathTerminated leave is False
869188 dot:arg
```

**Comment by ike709** [comment]
The bad code was an unindented `..()`
